server:
  port: 8085

spring:
  application:
    name: music-content-service

  datasource:
    url: jdbc:postgresql://localhost:5432/AudioCloud
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: music-content-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

jwt:
  secret: ${secretKey}
  expiration: 86400000

logging:
  level:
    root: ERROR
    KAFKA_CONSUMER: INFO
    ua.dymohlo.music_content_service: INFO
    org.apache.kafka: INFO
    org.springframework.kafka: INFO
    kafka: INFO
    org.springframework.cloud: INFO
    com.netflix: INFO
    org.springframework.web: ERROR
    org.springframework.security: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,refresh
  endpoint:
    health:
      show-details: always

kafka:
  topics:
    user-subscriptions: user-subscriptions

cache:
  user-subscription:
    key-prefix: "user:subscription:"
    ttl-hours: 24
