server:
  port: 8094

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/AudioCloud
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

logging:
  level:
    org.springframework.security: DEBUG
    ua.dymohlo.user_service: DEBUG

jwt:
  secret: ${secretKey}
  expiration: 86400000

subscription:
  service-name: subscription-service
  scheme: http
  api:
    base-path: "/api/v1"
    subscriptions-endpoint: "/subscriptions"

payment:
  service-name: payment-service
  scheme: http
  api:
    base-path: "/api/v1"
    process-endpoint: "/payment"
  default-provider: "liqpay"

kafka:
  topics:
    user-subscriptions: user-subscriptions
    user-deleted: user-deleted

saga:
  internal-api-key: "saga-internal-key-9f2e8d7c6b5a4918273645ebf0c1a2d3e4f5g6h7i8j9k0l1m2n3o4p5q6r7s8t9u0v1w2x3y4z5"